### ISSUE TITLE
Issue with empire fleet form in the game setup menu

### ISSUE THREAD

**Issue by lortael** [MetasharpNet/StarWarsRebellionEditor.NET#1]
# Issue
When attempting to modify the initial fleet present at Coruscant, only alliance units are available to add into capital ships:
![image](https://github.com/MetasharpNet/StarWarsRebellionEditor.NET/assets/9745041/126f9b61-5ca2-4d82-b366-1ffcc16a2371)

Also, the list of capital ships includes the ships from both sides:
![image](https://github.com/MetasharpNet/StarWarsRebellionEditor.NET/assets/9745041/2388c326-1996-49d9-a18b-589fa34bceed)

Concerning the ships, the same is also true for the alliance fleet setup, ships as well as units from the empire are also available. That may be a choice on your part but I think it makes editing the initial fleets a bit tedious as one have to be careful to pick the right ones.

# Suggestion
I cannot push a branch on the repo (permission denied) to propose a pull request so I open this issue instead.

As I cannot attach the CS files to the issue, here are the identified files in which I think the issue comes from:
StarWarsRebellionEditor.NET\SwRebellionEditor\Forms\EmpireFleetTableForm.cs
-> lines 22 to 24:
```
groupComboBox.Items.AddRange(Identifier.EmpireCapitalShips);
groupComboBox.Items.AddRange(Identifier.AllianceCapitalShips);
itemComboBox.Items.AddRange(Identifier.AllianceUnits);
```
should be in my opinion:
```        
groupComboBox.Items.AddRange(Identifier.EmpireCapitalShips);
itemComboBox.Items.AddRange(Identifier.EmpireUnits);
```

StarWarsRebellionEditor.NET\SwRebellionEditor\Forms\AllianceFleetTableForm.cs
-> lines 21 to 24:
```
groupComboBox.Items.AddRange(Identifier.AllianceCapitalShips);
groupComboBox.Items.AddRange(Identifier.EmpireCapitalShips);
itemComboBox.Items.AddRange(Identifier.AllianceUnits);
itemComboBox.Items.AddRange(Identifier.EmpireUnits);
```
should be:
```        
groupComboBox.Items.AddRange(Identifier.AllianceCapitalShips);
itemComboBox.Items.AddRange(Identifier.AllianceUnits);
```

I tested it and it seems to work as intended (here for the empire part):
![image](https://github.com/MetasharpNet/StarWarsRebellionEditor.NET/assets/9745041/8124356f-1292-4d97-ad0a-b92357b423c0)
![image](https://github.com/MetasharpNet/StarWarsRebellionEditor.NET/assets/9745041/72be6010-cc2c-424e-8dc1-64de4718bfd6)

Oh, and by the way, very nice work on the whole editor, its quite refreshing to go from Rebed to this one !

**Comment by MetasharpDev** [comment]
I'll check that

**Comment by MetasharpDev** [comment]
I made both sides available on purpose.
It allows to make tests to see all ships for us to debug in a single 3D battle :)

**Comment by lortael** [comment]
Right, I did not think about that aspect, that makes sense ;)
Then the only issue would be the empire fleet screen displaying only the alliance units.

**Comment by MetasharpDev** [comment]
I fixed it, will released it with my next update, are you on discord?
In fact, aside from testing aspects, it can also be used to build custom scenarios where ships were captured for example.
